# Site settings
title: Spencer Harrison
email: hello@spenhar.com
description: > # this means to ignore newlines until "baseurl:"
  Personal portfolio and writings of Spencer Harrison (@spenhar)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spenhar.com" # the base hostname & protocol for your site
twitter_username: spenhar
github_username:  spenhar

# Build settings
markdown: kramdown

#Exclude files
exclude: [node_modules, gulpfile.js]
