# Site settings
title: Spencer Harrison
email: spencerjharrison@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Strategic, interdisciplinary design for the everybody.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spenhar.com/" # the base hostname & protocol for your site
twitter_username: spenhar
github_username:  spenhar

# Build settings
markdown: kramdown
