# Site settings
title: spenhar
email: hello@spenhar.com
description: > # this means to ignore newlines until "baseurl:"
  Personal portfolio and writings of Spencer Harrison (@spenhar)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spenhar.com" # the base hostname & protocol for your site
twitter_username: spenhar
github_username:  spenhar
sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown

#Exclude files
exclude: [node_modules, gulpfile.js]

collections:
  _albums:
  _works:
  output: true
  permalink: /portfolio/:path/
